package docsite

// Fenced code blocks, highlighted by chroma.
//
// This replaces github.com/yuin/goldmark-highlighting/v2, whose last commit is
// from 2023. Of that extension the site used one path: look the block's
// language up in chroma, format it with CSS classes, and wrap it. That path
// is the forty lines below, calling chroma directly, and produces the same
// bytes (proved by building a site with both and diffing it). What it leaves
// out is what the site never used: guessing a language, inline styles, line
// numbers and per-block attributes.

import (
	"bytes"
	"fmt"

	"github.com/alecthomas/chroma/v2"
	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/lexers"
	"github.com/alecthomas/chroma/v2/styles"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/renderer"
	ghtml "github.com/yuin/goldmark/renderer/html"
	"github.com/yuin/goldmark/util"
)

// Chroma's two GitHub styles, one per colour scheme. Written out as CSS
// classes by syntaxCSS rather than inlined into every <span>, because inline
// colours cannot follow prefers-color-scheme: a light theme's dark-blue
// keyword is unreadable on a dark background.
const (
	lightStyle = "github"
	darkStyle  = "github-dark"
)

// syntaxFile is the highlighting stylesheet the build writes beside style.css.
const syntaxFile = "syntax.css"

// codeBlocks renders every fenced block in a <div> that names its language,
// so the stylesheet can label it and the page script can give it a copy
// button that does not scroll away with a long line.
//
// Only a block that names a language chroma knows is highlighted. An
// unlabelled block is usually command output and stays plain: guessing a
// lexer for "PASS: JS -> Go" colours it as whatever chroma thinks it
// resembles, which is noise pretending to be meaning.
type codeBlocks struct{}

func (codeBlocks) Extend(m goldmark.Markdown) {
	// 200 beats goldmark's own renderer (1000): the smaller number wins.
	m.Renderer().AddOptions(renderer.WithNodeRenderers(util.Prioritized(codeBlockRenderer{}, 200)))
}

type codeBlockRenderer struct{}

func (codeBlockRenderer) RegisterFuncs(reg renderer.NodeRendererFuncRegisterer) {
	reg.Register(ast.KindFencedCodeBlock, renderCodeBlock)
}

var (
	codeFormatter = chromahtml.New(chromahtml.WithClasses(true))
	codeStyle     = styles.Get(lightStyle)
)

func renderCodeBlock(w util.BufWriter, src []byte, node ast.Node, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkContinue, nil
	}
	n := node.(*ast.FencedCodeBlock)
	lang := n.Language(src)

	var code bytes.Buffer
	for i := 0; i < n.Lines().Len(); i++ {
		line := n.Lines().At(i)
		code.Write(line.Value(src))
	}

	_, _ = w.WriteString(`<div class="codeblock"`)
	if len(lang) > 0 {
		_, _ = w.WriteString(` data-lang="`)
		_, _ = w.Write(util.EscapeHTML(lang))
		_ = w.WriteByte('"')
	}
	_ = w.WriteByte('>')

	if lexer := lexerFor(lang); lexer != nil {
		if it, err := chroma.Coalesce(lexer).Tokenise(nil, code.String()); err == nil {
			// The style decides nothing visible here: with classes, colours
			// come from syntax.css.
			if err := codeFormatter.Format(w, codeStyle, it); err != nil {
				return ast.WalkStop, err
			}
			_, _ = w.WriteString("</div>\n")
			return ast.WalkContinue, nil
		}
	}
	_, _ = w.WriteString("<pre><code>")
	ghtml.DefaultWriter.RawWrite(w, code.Bytes())
	_, _ = w.WriteString("</code></pre></div>\n")
	return ast.WalkContinue, nil
}

func lexerFor(lang []byte) chroma.Lexer {
	if len(lang) == 0 {
		return nil
	}
	return lexers.Get(string(lang))
}

// syntaxCSS is the highlighting stylesheet: the light style, then the dark one,
// each inside its own prefers-color-scheme query. Generated from chroma at
// build time, so a chroma upgrade that renames a token class cannot leave the
// stylesheet colouring classes that no longer exist.
func syntaxCSS() ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("/* Generated by docsite from chroma's " + lightStyle + " and " + darkStyle + " styles. Do not edit. */\n")
	light, dark := styles.Get(lightStyle), styles.Get(darkStyle)
	// styles.Get returns the fallback rather than nil for an unknown name, so
	// a renamed style would silently produce a stylesheet in the wrong theme.
	if light.Name != lightStyle || dark.Name != darkStyle {
		return nil, fmt.Errorf("chroma has no %q or %q style (got %q, %q)", lightStyle, darkStyle, light.Name, dark.Name)
	}
	// Both scoped, not light as the default with dark overriding it: the two
	// styles do not colour the same token types (github colours punctuation,
	// github-dark leaves it to inherit), so unscoped light rules made every
	// brace in a dark-mode JSON block near-black on near-black.
	b.WriteString("@media not all and (prefers-color-scheme: dark) {\n")
	if err := codeFormatter.WriteCSS(&b, light); err != nil {
		return nil, err
	}
	b.WriteString("}\n")
	b.WriteString("@media (prefers-color-scheme: dark) {\n")
	if err := codeFormatter.WriteCSS(&b, dark); err != nil {
		return nil, err
	}
	b.WriteString("}\n")
	return b.Bytes(), nil
}
