# This file was generated by GoReleaser. DO NOT EDIT.
cask "irgo-winvm" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "351b0ac26ef2a0e380cb1325b04dd6ead3aa7b1facc6a451fd32394593d0e705"
      url "https://github.com/joeblew999/irgo-windows-vm/releases/download/v#{version}/irgo-winvm-darwin-arm64"
      binary "irgo-winvm-darwin-arm64", target: "irgo-winvm"
    end
    on_intel do
      sha256 "541778d2e103b3c3007f0385cd0c83e73af2c3344d0e9529307c546ec773b8bb"
      url "https://github.com/joeblew999/irgo-windows-vm/releases/download/v#{version}/irgo-winvm-darwin-amd64"
      binary "irgo-winvm-darwin-amd64", target: "irgo-winvm"
    end
  end
  on_linux do
    on_arm do
      sha256 "3e154cd8e89671299a638657d67314caa0005dd02a2970a9cfef3834e25f45b4"
      url "https://github.com/joeblew999/irgo-windows-vm/releases/download/v#{version}/irgo-winvm-linux-arm64"
      binary "irgo-winvm-linux-arm64", target: "irgo-winvm"
    end
    on_intel do
      sha256 "a6a7d5221ca5883feee81e30d88a39855d9d4078818e3d477e47d4f216a9905f"
      url "https://github.com/joeblew999/irgo-windows-vm/releases/download/v#{version}/irgo-winvm-linux-amd64"
      binary "irgo-winvm-linux-amd64", target: "irgo-winvm"
    end
  end

  name "irgo-winvm"
  desc "Run a Go program built on your Mac on a real Windows 11 ARM64 VM"
  homepage "https://joeblew999.github.io/irgo-windows-vm/"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Next: irgo-winvm doctor
    For an AI agent: claude mcp add irgo-winvm -- irgo-winvm mcp
  EOS
end
