# This file was generated by GoReleaser. DO NOT EDIT.
cask "irgo-winvm" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "25a40ceab1e55148250b5034c442350f652fd774ec92f9751dfb38d560defc67"
      url "https://github.com/joeblew999/irgo-windows-vm/releases/download/v#{version}/irgo-winvm-darwin-arm64"
      binary "irgo-winvm-darwin-arm64", target: "irgo-winvm"
    end
    on_intel do
      sha256 "874e7c842a79f102a0aea7599e264d4dd010fb395a287a0270a72024df39fee8"
      url "https://github.com/joeblew999/irgo-windows-vm/releases/download/v#{version}/irgo-winvm-darwin-amd64"
      binary "irgo-winvm-darwin-amd64", target: "irgo-winvm"
    end
  end
  on_linux do
    on_arm do
      sha256 "dbe9f19921bd34d3d296f85381f69191e7f7995534016c1f52cb8abaf7f17767"
      url "https://github.com/joeblew999/irgo-windows-vm/releases/download/v#{version}/irgo-winvm-linux-arm64"
      binary "irgo-winvm-linux-arm64", target: "irgo-winvm"
    end
    on_intel do
      sha256 "dc4ce1e5472963dcc9f03ae8622a3f5d1c471cbbe05d1a4016babd5c41d9ab2a"
      url "https://github.com/joeblew999/irgo-windows-vm/releases/download/v#{version}/irgo-winvm-linux-amd64"
      binary "irgo-winvm-linux-amd64", target: "irgo-winvm"
    end
  end

  name "irgo-winvm"
  desc "Run a Go program built on your Mac on a real Windows 11 ARM64 VM"
  homepage "https://joeblew999.github.io/irgo-windows-vm/"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Next: irgo-winvm doctor
    For an AI agent: claude mcp add irgo-winvm -- irgo-winvm mcp
  EOS
end
