# This file was generated by GoReleaser. DO NOT EDIT.
cask "irgo-winvm" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "cb2edd397a89c2c4c862def6f77938fdf9a6f8d2cc50063836c1a568e331bc1f"
      url "https://github.com/joeblew999/irgo-windows-vm/releases/download/v#{version}/irgo-winvm-darwin-arm64"
      binary "irgo-winvm-darwin-arm64", target: "irgo-winvm"
    end
    on_intel do
      sha256 "73cd5984a053e5dbad849d6e91686ec6c1fb275347cf08fa233b776f9fa28b94"
      url "https://github.com/joeblew999/irgo-windows-vm/releases/download/v#{version}/irgo-winvm-darwin-amd64"
      binary "irgo-winvm-darwin-amd64", target: "irgo-winvm"
    end
  end
  on_linux do
    on_arm do
      sha256 "1e6665eb4ee3de8f13323d713bb44050200bdcfe51eb1cc22db957731ad2f0af"
      url "https://github.com/joeblew999/irgo-windows-vm/releases/download/v#{version}/irgo-winvm-linux-arm64"
      binary "irgo-winvm-linux-arm64", target: "irgo-winvm"
    end
    on_intel do
      sha256 "49c432c65df9110649173781cb76b544343fc0a675d9d86ac2548ade5bcdace7"
      url "https://github.com/joeblew999/irgo-windows-vm/releases/download/v#{version}/irgo-winvm-linux-amd64"
      binary "irgo-winvm-linux-amd64", target: "irgo-winvm"
    end
  end

  name "irgo-winvm"
  desc "Run a Go program built on your Mac on a real Windows 11 ARM64 VM"
  homepage "https://joeblew999.github.io/irgo-windows-vm/"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Next: irgo-winvm doctor
    For an AI agent: claude mcp add irgo-winvm -- irgo-winvm mcp
  EOS
end
