// Package openapi renders wire's route table as an OpenAPI 3.1 document.
//
// It reflects over the request and response types, so it is kept out of
// package wire, which the TinyGo Worker compiles. The Worker serves the
// document from a file generated by this package at build time
// (worker/openapi.json, written by `mise run worker:wasm`); a worker test
// fails while that file differs from what Document returns now.
package openapi

import (
	"encoding/json"
	"net/http"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/joeblew999/irgo-windows-vm/wire"
)

type obj = map[string]any

// Document is the API as OpenAPI 3.1 JSON, indented, ending in a newline.
// The same table always gives the same bytes: maps are encoded sorted.
func Document() ([]byte, error) {
	g := gen{schemas: obj{}}
	g.schemas["Error"] = g.schema(reflect.TypeOf(wire.Error{}))

	paths := obj{}
	for _, r := range wire.Routes {
		p := openAPIPath(r.Path)
		item, _ := paths[p].(obj)
		if item == nil {
			item = obj{}
			paths[p] = item
		}
		item[strings.ToLower(r.Method)] = g.operation(r)
	}

	security := obj{}
	for _, s := range wire.Scopes {
		security[string(s.Scope)] = obj{
			"type": "http", "scheme": "bearer",
			"description": s.Summary + ". The Worker's secret " + s.Secret + "; clients read it from " + s.Env + ".",
		}
	}

	var codes []string
	for _, c := range wire.Codes {
		codes = append(codes, "`"+string(c.Code)+"` ("+strconv.Itoa(c.Status)+"): "+c.Summary)
	}
	doc := obj{
		"openapi": "3.1.0",
		"info": obj{
			"title":   "irgo-windows-vm Worker",
			"version": wire.APIVersion,
			"description": "The Cloudflare Worker's API: live glaze status and the private golden image. " +
				"Generated from the route table in wire/routes.go, the same table the Worker routes by and the clients build URLs from. " +
				"Every error is an Error whose code is one of: " + strings.Join(codes, "; ") + ".",
		},
		"paths":      paths,
		"components": obj{"schemas": g.schemas, "securitySchemes": security},
	}
	b, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

// openAPIPath writes {key...} as {key}: OpenAPI has no rest parameter, so
// the parameter's description says it spans segments.
func openAPIPath(p string) string { return strings.ReplaceAll(p, "...}", "}") }

type gen struct{ schemas obj }

func (g gen) operation(r wire.Route) obj {
	op := obj{
		"operationId": r.Name,
		"summary":     r.Summary,
		"x-scope":     string(r.Scope),
	}
	if len(r.Commands) > 0 {
		op["x-irgo-winvm-commands"] = r.Commands
	}
	if r.Scope == wire.ScopeNone {
		op["security"] = []any{}
	} else {
		op["security"] = []any{obj{string(r.Scope): []any{}}}
	}

	var params []any
	for _, p := range append(append([]wire.Param{}, r.Params...), r.Headers...) {
		desc := p.Summary
		if strings.Contains(r.Path, "{"+p.Name+"...}") {
			desc += " (spans path segments: its slashes are not escaped)"
		}
		params = append(params, obj{
			"name": p.Name, "in": p.In, "required": p.In == "path" || strings.HasPrefix(p.Summary, "required"),
			"description": desc, "schema": obj{"type": "string"},
		})
	}
	if params != nil {
		op["parameters"] = params
	}

	if r.RequestType != "" {
		content := obj{}
		switch {
		case r.Request != nil:
			content[r.RequestType] = obj{"schema": g.schema(reflect.TypeOf(r.Request))}
		case r.RequestType == wire.TypeMultipart:
			content[r.RequestType] = obj{"schema": obj{
				"type":        "object",
				"description": "one part named " + wire.GlazeManifestPart + " holding shots.json, and one part per picture it names, named by its file name (at most " + strconv.Itoa(wire.MaxPictures) + ", each a PNG of at most " + strconv.Itoa(wire.MaxPictureBytes) + " bytes)",
				"required":    []string{wire.GlazeManifestPart},
				"properties": obj{wire.GlazeManifestPart: obj{
					"type": "string", "contentMediaType": wire.TypeJSON,
				}},
				"additionalProperties": obj{"type": "string", "contentMediaType": "image/png"},
			}}
		default:
			content[r.RequestType] = obj{"schema": obj{"type": "string", "contentMediaType": r.RequestType}}
		}
		op["requestBody"] = obj{"required": true, "content": content}
		op["x-max-body"] = r.MaxBody
	}

	responses := obj{}
	ok := obj{"description": http.StatusText(r.Success)}
	if r.ResponseType != "" {
		var s any = obj{}
		switch {
		case r.Response != nil:
			s = g.schema(reflect.TypeOf(r.Response))
		case r.ResponseType != wire.TypeJSON:
			s = obj{"type": "string", "contentMediaType": r.ResponseType}
		}
		ok["content"] = obj{r.ResponseType: obj{"schema": s}}
	}
	if len(r.ResponseHeaders) > 0 {
		h := obj{}
		for _, p := range r.ResponseHeaders {
			h[p.Name] = obj{"description": p.Summary, "schema": obj{"type": "string"}}
		}
		ok["headers"] = h
	}
	responses[strconv.Itoa(r.Success)] = ok
	for _, s := range r.Also {
		alt := obj{}
		for k, v := range ok {
			alt[k] = v
		}
		alt["description"] = http.StatusText(s)
		responses[strconv.Itoa(s)] = alt
	}

	byStatus := map[int][]string{}
	for _, c := range r.Errs() {
		byStatus[c.Status()] = append(byStatus[c.Status()], string(c))
	}
	for status, cs := range byStatus {
		sort.Strings(cs)
		e := obj{"description": "code " + strings.Join(cs, " or ")}
		if r.Method != http.MethodHead {
			e["content"] = obj{wire.TypeJSON: obj{"schema": obj{"$ref": "#/components/schemas/Error"}}}
		}
		responses[strconv.Itoa(status)] = e
	}
	op["responses"] = responses
	return op
}

var (
	timeType = reflect.TypeOf(time.Time{})
	rawType  = reflect.TypeOf(json.RawMessage{})
	codeType = reflect.TypeOf(wire.Code(""))
)

// schema is t as a JSON Schema. A named struct or map from package wire goes
// in components and is referred to.
func (g gen) schema(t reflect.Type) any {
	switch t {
	case timeType:
		return obj{"type": "string", "format": "date-time"}
	case rawType:
		return obj{"description": "any JSON, stored and returned as it was posted"}
	case codeType:
		var enum []string
		for _, c := range wire.Codes {
			enum = append(enum, string(c.Code))
		}
		return obj{"type": "string", "enum": enum}
	}
	named := t.Name() != "" && t.PkgPath() == reflect.TypeOf(wire.Health{}).PkgPath()
	if named {
		if _, done := g.schemas[t.Name()]; !done {
			g.schemas[t.Name()] = obj{} // a recursive type stops here
			g.schemas[t.Name()] = g.inline(t)
		}
		return obj{"$ref": "#/components/schemas/" + t.Name()}
	}
	return g.inline(t)
}

func (g gen) inline(t reflect.Type) any {
	switch t.Kind() {
	case reflect.Pointer:
		return obj{"anyOf": []any{g.schema(t.Elem()), obj{"type": "null"}}}
	case reflect.String:
		return obj{"type": "string"}
	case reflect.Bool:
		return obj{"type": "boolean"}
	case reflect.Int, reflect.Int64, reflect.Int32, reflect.Uint, reflect.Uint64, reflect.Uint32:
		return obj{"type": "integer"}
	case reflect.Slice:
		return obj{"type": "array", "items": g.schema(t.Elem())}
	case reflect.Map:
		return obj{"type": "object", "additionalProperties": g.schema(t.Elem())}
	case reflect.Struct:
		props, required := obj{}, []string{}
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			if !f.IsExported() {
				continue
			}
			name, opts, _ := strings.Cut(f.Tag.Get("json"), ",")
			if name == "-" {
				continue
			}
			if f.Anonymous && name == "" && f.Type.Kind() == reflect.Struct {
				// encoding/json puts an embedded struct's fields in this one.
				e := g.inline(f.Type).(obj)
				for k, v := range e["properties"].(obj) {
					props[k] = v
				}
				required = append(required, e["required"].([]string)...)
				continue
			}
			if name == "" {
				name = f.Name
			}
			props[name] = g.schema(f.Type)
			if !strings.Contains(opts, "omitempty") {
				required = append(required, name)
			}
		}
		return obj{"type": "object", "properties": props, "required": required}
	}
	return obj{}
}
