// Package utmvm generates UTM virtual machine bundles without the UTM GUI.
//
// A .utm is a directory holding config.plist plus a Data/ subdirectory. UTM
// discovers bundles in its Documents folder at launch, so writing one there is
// equivalent to clicking through the wizard — but repeatable, diffable and
// runnable from CI.
//
// The plist is emitted as plain XML rather than through a plist library: the
// document is a fixed shape, and the schema is version-specific enough that
// being able to read the exact bytes we produce is worth more than the
// abstraction. Every field below was verified against UTM's own Swift source
// at the v4.7.5 tag, not main — main was two majors ahead and disagreed.
package utmvm

import (
	"fmt"
	"strings"
)

// Config describes a VM to generate. Zero values are not useful; use NewConfig.
type Config struct {
	Name       string
	UUID       string
	MemoryMiB  int
	CPUCount   int
	MACAddress string

	// Drives are emitted in order. Order matters: UTM assigns bootindex by
	// position, so the install medium must precede anything optional.
	Drives []Drive
}

// Drive is one entry in the VM's drive list.
type Drive struct {
	ID        string
	ImageName string // filename inside Data/
	Type      DriveType
	Interface DriveInterface
	ReadOnly  bool
}

type DriveType string

const (
	DriveDisk DriveType = "Disk"
	DriveCD   DriveType = "CD"
)

type DriveInterface string

const (
	// NVMe is required for the Windows system disk: Windows ARM64 has no inbox
	// VirtIO driver, so a VirtIO disk is invisible to Setup and it reports that
	// no drive can be found.
	IfaceNVMe   DriveInterface = "NVMe"
	IfaceUSB    DriveInterface = "USB"
	IfaceVirtIO DriveInterface = "VirtIO"
)

// displayHardware must be virtio-ramfb-gl for Windows on aarch64.
//
// virtio-gpu-pci provides no framebuffer until a guest driver loads, and the
// arm "virt" machine has no legacy VGA to fall back on. The guest then boots
// with no output at all, which is indistinguishable from a hang — including
// the "Press any key to boot from CD" prompt being invisible. UTM's own wizard
// picks the ramfb variant for Windows guests for exactly this reason.
const displayHardware = "virtio-ramfb-gl"

// plistTemplate is the UTM v4 QEMU configuration.
//
// Two fields here are load-bearing and easy to lose to a "cleanup":
//
//   - PS2Controller is decoded with a non-optional decode() and has no default.
//     Omitting it fails the whole document with a generic "cannot import" error
//     that names no field.
//   - UsbBusSupport is an enum whose raw values are "2.0" and "3.0". "USB3_0"
//     looks plausible and is rejected the same opaque way.
const plistTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>ConfigurationVersion</key><integer>4</integer>
  <key>Backend</key><string>QEMU</string>

  <key>Information</key>
  <dict>
    <key>Name</key><string>%s</string>
    <key>UUID</key><string>%s</string>
    <key>Icon</key><string>windows</string>
    <key>IconCustom</key><false/>
    <key>Notes</key><string>Generated by irgo-windows-vm. Unattended Windows 11 ARM64; login dev/dev, RDP enabled.</string>
  </dict>

  <key>System</key>
  <dict>
    <key>Architecture</key><string>aarch64</string>
    <key>Target</key><string>virt</string>
    <key>MemorySize</key><integer>%d</integer>
    <key>CPU</key><string>host</string>
    <key>CPUCount</key><integer>%d</integer>
    <key>CPUFlagsAdd</key><array/>
    <key>CPUFlagsRemove</key><array/>
    <key>ForceMulticore</key><false/>
    <key>JITCacheSize</key><integer>0</integer>
  </dict>

  <key>QEMU</key>
  <dict>
    <key>Hypervisor</key><true/>
    <key>UEFIBoot</key><true/>
    <key>TPMDevice</key><true/>
    <key>RNGDevice</key><true/>
    <key>BalloonDevice</key><true/>
    <key>PS2Controller</key><false/>
    <key>RTCLocalTime</key><true/>
    <key>TSO</key><false/>
    <key>DebugLog</key><false/>
    <key>MachinePropertyOverride</key><string></string>
    <key>AdditionalArguments</key><array/>
  </dict>

  <key>Drive</key>
  <array>
%s  </array>

  <key>Display</key>
  <array>
    <dict>
      <key>Hardware</key><string>%s</string>
      <key>DynamicResolution</key><true/>
      <key>NativeResolution</key><false/>
      <key>UpscalingFilter</key><string>Linear</string>
      <key>DownscalingFilter</key><string>Linear</string>
    </dict>
  </array>

  <key>Network</key>
  <array>
    <dict>
      <key>Mode</key><string>Shared</string>
      <key>Hardware</key><string>virtio-net-pci</string>
      <key>MacAddress</key><string>%s</string>
      <key>IsolateFromHost</key><false/>
      <key>PortForward</key><array/>
    </dict>
  </array>

  <key>Sound</key>
  <array>
    <dict><key>Hardware</key><string>intel-hda</string></dict>
  </array>

  <key>Serial</key><array/>

  <key>Input</key>
  <dict>
    <key>UsbBusSupport</key><string>3.0</string>
    <key>UsbSharing</key><true/>
    <key>MaximumUsbShare</key><integer>3</integer>
  </dict>

  <key>Sharing</key>
  <dict>
    <key>ClipboardSharing</key><true/>
    <key>DirectoryShareMode</key><string>None</string>
    <key>DirectoryShareReadOnly</key><false/>
  </dict>
</dict>
</plist>
`

const driveTemplate = `    <dict>
      <key>Identifier</key><string>%s</string>
      <key>ImageName</key><string>%s</string>
      <key>ImageType</key><string>%s</string>
      <key>Interface</key><string>%s</string>
      <key>InterfaceVersion</key><integer>1</integer>
      <key>ReadOnly</key><%s/>
    </dict>
`

// Plist renders the configuration as a UTM v4 config.plist.
func (c Config) Plist() (string, error) {
	if c.Name == "" || c.UUID == "" {
		return "", fmt.Errorf("utmvm: config needs a Name and UUID")
	}
	if len(c.Drives) == 0 {
		return "", fmt.Errorf("utmvm: config needs at least one drive")
	}

	var drives strings.Builder
	for _, d := range c.Drives {
		ro := "false"
		if d.ReadOnly {
			ro = "true"
		}
		fmt.Fprintf(&drives, driveTemplate, d.ID, d.ImageName, d.Type, d.Interface, ro)
	}

	return fmt.Sprintf(plistTemplate,
		xmlEscape(c.Name), c.UUID,
		c.MemoryMiB, c.CPUCount,
		drives.String(),
		displayHardware,
		c.MACAddress,
	), nil
}

// xmlEscape covers the characters a VM name can plausibly contain. The plist is
// otherwise fixed text, so a full XML encoder would be more machinery than the
// problem needs.
func xmlEscape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;")
	return r.Replace(s)
}
